
#spring.profiles.active=dev
spring.application.name=dave-adapter-telraam
# prevent opening standard http port
spring.main.web-application-type=none

# Authentication for DAVe API
spring.security.oauth2.client.registration.dave.client-id=dave-adapter
spring.security.oauth2.client.registration.dave.client-secret=secret
spring.security.oauth2.client.registration.dave.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.dave.scope=openid
spring.security.oauth2.client.provider.dave.token-uri=http://localhost:8081/realms/dave/protocol/openid-connect/token

dave.api-url=http://localhost:8080

# Coordinates for Telraam API
telraam.api-url=https://telraam-api.net
telraam.api-key=apikey
telraam.bounding-box.min-lon=10.670709
telraam.bounding-box.min-lat=52.365772
telraam.bounding-box.max-lon=10.884599
telraam.bounding-box.max-lat=52.476114

# for the time being, this is a static mapping of segments to counting spots in DAVe
telraam.segment-mapping[0].segment-id=9000011165
telraam.segment-mapping[0].zaehlung-id=f6e155f4-89e9-4046-830a-ead29fa6d7a5

telraam.segment-mapping[1].segment-id=9000011166
telraam.segment-mapping[1].zaehlung-id=f6e155f4-89e9-4046-830a-ead29fa6d7a6

telraam.scheduler.cron=0 */15 * * * *

logging.level.de.starwit.telraam=INFO
logging.level.org.springframework.web.reactive.function.client=WARN
logging.level.org.springframework.security=WARN
