replicaCount: 1

image:
  repository: starwitorg/dave-adapter-telraam
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ${project.version}

spring:
  profiles:
    active: auth
  security:
    oauth2:
      client:
        registration:
          dave:
            client_id: dave_api
            client_secret: secret
        provider:
          dave:
            token_uri: https://uri


app:
  telraam:
    api_url: https://telraam-api.net
    api_key: yoursecretapikey
    bounding_box:
      min_lon: 10.670709
      min_lat: 52.365772
      max_lon: 10.884599
      max_lat: 52.476114

    # for the time being, this is a static mapping of segments to counting spots in DAVe
    segment_mapping:
      - segment_id: "9000011165"
        zaehlung_id: "287bb410-b00f-4816-a0f3-bb14c18ec0c4"
      - segment_id: "9000011362"
        zaehlung_id: "12e594b3-73d4-462e-9395-abaef59e7a89"

  scheduler:
    cron: 0 */15 * * * *

  dave_url: http://192.168.100.79:8080/detector/save-latest-detections
  auth: 
    enabled: true

service:
  port: 8080

# extraEnv: |
#   - name: JAVA_TOOL_OPTIONS
#     value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5000
#   - name: LOGGING_LEVEL_ROOT
#     value: DEBUG

autoscaling:
  enabled: false